steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'backend/Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ishigaki-trip-app'
      - 'backend'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ishigaki-trip-app']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ishigaki-trip-app'
      - '--image=gcr.io/$PROJECT_ID/ishigaki-trip-app'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
